# -*- coding: utf-8 -*-
"""walmart_Data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zBBjbTcsHwW1wEwLaA3QZQB0Fmox0Li
"""

import pandas as pd
import numpy as np

file_path = "/content/Online Retail.xlsx"  # Upload the Excel file to Colab
df = pd.read_excel(file_path)

print(df.shape)
df.head()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns)

df = df.dropna(subset=['customerid'])

df = df[df['quantity'] > 0]

df = df[df['unitprice'] > 0]

df['invoicedate'] = pd.to_datetime(df['invoicedate'])

df['invoicedate'] = df['invoicedate'].dt.strftime('%b-%Y')

df['totalprice'] = df['quantity'] * df['unitprice']

df = df.drop_duplicates()

df.to_excel('/content/online_retail_cleaned.xlsx', index=False)

print("✅ Cleaning complete. Cleaned file saved as 'online_retail_cleaned.xlsx'")